version: 2.1

jobs:
  build: 
      docker:
        - image: python:3.7.3-stretch

      working_directory: ~/repo
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              make install
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              sudo chmod +x /bin/hadolint
              
        
        # Installation for linting dockerfile
        # - run:
        #     name: install Hadolint
        #     command: |
        #       sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
        #       sudo chmod +x /bin/hadolint
              
        - run:
            name: run test/lint
            command: |
              . venv/bin/activate
              make lint

workflows:
  say-hello-workflow:
    jobs:
      - build

